### ISSUE TITLE
Plotnine not plotting multiple plots side-by-side

### ISSUE THREAD

**Issue by mlubej** [datascienceworkshops/r4ds-python-plotnine#3]
Hi!

I'm just going through the tutorial and noticed the following section:

![image](https://user-images.githubusercontent.com/37869250/97778657-e8c23800-1b78-11eb-8c78-71dc124fa706.png)

When I try to reproduce this using the same provided code, I only get the second plot to show and not both:

![image](https://user-images.githubusercontent.com/37869250/97778671-01325280-1b79-11eb-8eee-4d32178274f6.png)

Do you know what's going on?

Thanks!

**Comment by jeroenjanssens** [comment]
I have used a couple of tricks to let some plots appear side-by-side in the HTML version. In Jupyter Notebook, this is not possible with just `plotnine`.
